version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: flask-base-app
    command: sleep infinity
    volumes:
      - .:/home/flask/app
    ports:
      - 5000:5000
    depends_on:
      - db
